-- Seed do DE_PARA Omie (DRE/DFC) a partir do CSV do cliente.
-- Gerado automaticamente. Idempotente (ON CONFLICT atualiza a rubrica).

INSERT INTO public.omie_dre_mapa (codigo_categoria, descricao_categoria, rubrica, demonstrativo) VALUES
  ('1.1.1. Receita Assinaturas', '1.1.1. Receita Assinaturas', 'Receita de Assinaturas', 'dre'),
  ('1.1.1. Receita Assinaturas', '1.1.1. Receita Assinaturas', 'Receita de Assinaturas', 'dfc'),
  ('1.1.2. Receita Displays', '1.1.2. Receita Displays', 'Receita com Materiais', 'dre'),
  ('1.1.2. Receita Displays', '1.1.2. Receita Displays', 'Receita com Materiais', 'dfc'),
  ('1.1.3. Receita Markup', '1.1.3. Receita Markup', 'Receita Markup', 'dre'),
  ('1.1.3. Receita Markup', '1.1.3. Receita Markup', 'Receita Markup', 'dfc'),
  ('1.1.4. Serviços Para Clientes', '1.1.4. Serviços Para Clientes', 'Serviços para Clientes', 'dre'),
  ('1.1.4. Serviços Para Clientes', '1.1.4. Serviços Para Clientes', 'Receita de Serviços', 'dfc'),
  ('1.2.1. POCs e Editais', '1.2.1. POCs e Editais', '(+) Novos Empréstimos & Financiamentos', 'dfc'),
  ('1.2.2. Financeira', '1.2.2. Financeira', '(+) Receita financeira', 'dre'),
  ('1.2.2. Financeira', '1.2.2. Financeira', '(+) Receita financeira', 'dfc'),
  ('1.2.2.1. Juros Atraso', '1.2.2.1. Juros Atraso', '(-) Juros', 'dre'),
  ('1.2.2.1. Juros Atraso', '1.2.2.1. Juros Atraso', '(-) Juros', 'dfc'),
  ('1.2.2.2. Rendimentos Financeiros', '1.2.2.2. Rendimentos Financeiros', '(+) Receita financeira', 'dre'),
  ('1.2.2.2. Rendimentos Financeiros', '1.2.2.2. Rendimentos Financeiros', '(+) Receita financeira', 'dfc'),
  ('1.2.5. Corporates', '1.2.5. Corporates', 'Enterprise', 'dre'),
  ('1.2.5. Corporates', '1.2.5. Corporates', 'Entrada de Receita', 'dfc'),
  ('1.2.6 Subsídios e Transferências', '1.2.6 Subsídios e Transferências', '(+) Resultado Não Operacional', 'dre'),
  ('1.2.6 Subsídios e Transferências', '1.2.6 Subsídios e Transferências', '(+) Resultado Não Operacional', 'dfc'),
  ('1.3.2. Empréstimo Outros', '1.3.2. Empréstimo Outros', '(+) Novos Empréstimos & Financiamentos', 'dfc'),
  ('1.3.1. Empréstimo Bancário', '1.3.1. Empréstimo Bancário', '(+) Novos Empréstimos & Financiamentos', 'dfc'),
  ('1.3.3. Antecipaçao de Recebíveis', '1.3.3. Antecipaçao de Recebíveis', 'Antecipação da Receita', 'dfc'),
  ('1.3.4. Mútuo Conversível', '1.3.4. Mútuo Conversível', '(+) Novos Empréstimos & Financiamentos', 'dfc'),
  ('1.4.1. Estorno de taxa', '1.4.1. Estorno de taxa', '(+) Resultado Não Operacional', 'dre'),
  ('1.4.1. Estorno de taxa', '1.4.1. Estorno de taxa', '(+) Resultado Não Operacional', 'dfc'),
  ('1.4.2. Estorno de Compra', '1.4.2. Estorno de Compra', '(+) Resultado Não Operacional', 'dre'),
  ('1.4.2. Estorno de Compra', '1.4.2. Estorno de Compra', '(+) Resultado Não Operacional', 'dfc'),
  ('1.4.2. Estorno de compras', '1.4.2. Estorno de compras', '(+) Resultado Não Operacional', 'dre'),
  ('1.4.2. Estorno de compras', '1.4.2. Estorno de compras', '(+) Resultado Não Operacional', 'dfc'),
  ('2.1 Simples Nacional', '2.1 Simples Nacional', 'Simples Nacional', 'dre'),
  ('2.1 Simples Nacional', '2.1 Simples Nacional', 'Simples Nacional', 'dfc'),
  ('2.2 PIS', '2.2 PIS', 'PIS', 'dre'),
  ('2.2 PIS', '2.2 PIS', 'PIS', 'dfc'),
  ('2.3 COFINS', '2.3 COFINS', 'COFINS', 'dre'),
  ('2.3 COFINS', '2.3 COFINS', 'COFINS', 'dfc'),
  ('2.4 ISS', '2.4 ISS', 'ISS', 'dre'),
  ('2.4 ISS', '2.4 ISS', 'ISS', 'dfc'),
  ('2.5 ICMS', '2.5 ICMS', 'ICMS', 'dre'),
  ('2.5 ICMS', '2.5 ICMS', 'ICMS', 'dfc'),
  ('2.10 IPTU', '2.10 IPTU', 'Ocupação & Escritório', 'dre'),
  ('2.10 IPTU', '2.10 IPTU', 'Ocupação & Escritório', 'dfc'),
  ('2.6 Parcelamento de Impostos', '2.6 Parcelamento de Impostos', 'Parcelamento de Impostos', 'dfc'),
  ('2.7 IRF', '2.7 IRF', 'IRF', 'dre'),
  ('2.7 IRF', '2.7 IRF', 'IRF', 'dfc'),
  ('2.8 Retenção de Contribuição', '2.8 Retenção de Contribuição', 'Retenção de Contribuição', 'dfc'),
  ('3.1.1.1. Pessoal - Administrativo', '3.1.1.1. Pessoal - Administrativo', 'Equipe Administrativa', 'dre'),
  ('3.1.1.1. Pessoal - Administrativo', '3.1.1.1. Pessoal - Administrativo', 'Equipe Administrativa', 'dfc'),
  ('3.1.1.14 Pessoal - Automações', '3.1.1.14 Pessoal - Automações', 'Equipe Administrativa', 'dre'),
  ('3.1.1.14 Pessoal - Automações', '3.1.1.14 Pessoal - Automações', 'Equipe Administrativa', 'dfc'),
  ('3.1.1.10 Pro Labore', '3.1.1.10 Pro Labore', 'Equipe Administrativa', 'dre'),
  ('3.1.1.10 Pro Labore', '3.1.1.10 Pro Labore', 'Equipe Administrativa', 'dfc'),
  ('3.1.1.10 Premiação - Suporte', '3.1.1.10 Premiação - Suporte', 'Premiações Operacionais', 'dre'),
  ('3.1.1.10 Premiação - Suporte', '3.1.1.10 Premiação - Suporte', 'Premiações Operacionais', 'dfc'),
  ('3.1.1.10 Pessoal - Novos Canais', '3.1.1.10 Pessoal - Novos Canais', 'Equipe Comercial', 'dre'),
  ('3.1.1.10 Pessoal - Novos Canais', '3.1.1.10 Pessoal - Novos Canais', 'Equipe Comercial', 'dfc'),
  ('3.1.1.15 Premiação - Novos Canais', '3.1.1.15 Premiação - Novos Canais', 'Premiações', 'dre'),
  ('3.1.1.15 Premiação - Novos Canais', '3.1.1.15 Premiação - Novos Canais', 'Premiações', 'dfc'),
  ('3.1.1.11 Premiação - Sucesso', '3.1.1.11 Premiação - Sucesso', 'Premiações Operacionais', 'dre'),
  ('3.1.1.11 Premiação - Sucesso', '3.1.1.11 Premiação - Sucesso', 'Premiações Operacionais', 'dfc'),
  ('3.1.1.2. Pessoal - Comercial', '3.1.1.2. Pessoal - Comercial', 'Equipe Comercial', 'dre'),
  ('3.1.1.2. Pessoal - Comercial', '3.1.1.2. Pessoal - Comercial', 'Equipe Comercial', 'dfc'),
  ('3.1.1.3. Pessoal - Marketing', '3.1.1.3. Pessoal - Marketing', 'Equipe Marketing', 'dre'),
  ('3.1.1.3. Pessoal - Marketing', '3.1.1.3. Pessoal - Marketing', 'Equipe Marketing', 'dfc'),
  ('3.1.1.4. Pessoal - Tecnologia', '3.1.1.4. Pessoal - Tecnologia', 'Equipe Tecnologia', 'dre'),
  ('3.1.1.4. Pessoal - Tecnologia', '3.1.1.4. Pessoal - Tecnologia', 'Equipe Tecnologia', 'dfc'),
  ('3.1.1.5. Premiação - Comercial', '3.1.1.5. Premiação - Comercial', 'Premiações', 'dre'),
  ('3.1.1.5. Premiação - Comercial', '3.1.1.5. Premiação - Comercial', 'Premiações', 'dfc'),
  ('3.1.1.6. Premiação - Onboarding', '3.1.1.6. Premiação - Onboarding', 'Premiações', 'dre'),
  ('3.1.1.6. Premiação - Onboarding', '3.1.1.6. Premiação - Onboarding', 'Premiações', 'dfc'),
  ('3.1.1.6. Premiação - Operação', '3.1.1.6. Premiação - Operação', 'Premiações', 'dre'),
  ('3.1.1.6. Premiação - Operação', '3.1.1.6. Premiação - Operação', 'Premiações', 'dfc'),
  ('3.1.1.7. INSS', '3.1.1.7. INSS', 'Encargos Sociais', 'dre'),
  ('3.1.1.7. INSS', '3.1.1.7. INSS', 'Encargos sociais', 'dfc'),
  ('3.1.1.12. IRRF sob Salarios', '3.1.1.12. IRRF sob Salarios', 'Encargos Sociais', 'dre'),
  ('3.1.1.12. IRRF sob Salarios', '3.1.1.12. IRRF sob Salarios', 'Encargos sociais', 'dfc'),
  ('3.1.1.8 Premiação - Marketing', '3.1.1.8 Premiação - Marketing', 'Premiações', 'dre'),
  ('3.1.1.8 Premiação - Marketing', '3.1.1.8 Premiação - Marketing', 'Premiações', 'dfc'),
  ('3.1.1.9 Benefícios - Colaboradores', '3.1.1.9 Benefícios - Colaboradores', 'Benefícios', 'dre'),
  ('3.1.1.9 Benefícios - Colaboradores', '3.1.1.9 Benefícios - Colaboradores', 'Benefícios', 'dfc'),
  ('3.1.2.03 Consultorias - Administrativo', '3.1.2.03 Consultorias - Administrativo', 'Assessorias & Consultorias', 'dre'),
  ('3.1.2.03 Consultorias - Administrativo', '3.1.2.03 Consultorias - Administrativo', 'Assessorias & Consultorias', 'dfc'),
  ('3.1.2.07 Aluguel - Administrativo', '3.1.2.07 Aluguel - Administrativo', 'Ocupação & Escritório', 'dre'),
  ('3.1.2.07 Aluguel - Administrativo', '3.1.2.07 Aluguel - Administrativo', 'Ocupação & Escritório', 'dfc'),
  ('3.1.2.1 Softwares - Administrativo', '3.1.2.1 Softwares - Administrativo', 'Softwares Administrativos', 'dre'),
  ('3.1.2.1 Softwares - Administrativo', '3.1.2.1 Softwares - Administrativo', 'Softwares Administrativos', 'dfc'),
  ('3.1.2.10 Telefone e Internet - Administrativo', '3.1.2.10 Telefone e Internet - Administrativo', 'Ocupação & Escritório', 'dre'),
  ('3.1.2.10 Telefone e Internet - Administrativo', '3.1.2.10 Telefone e Internet - Administrativo', 'Ocupação & Escritório', 'dfc'),
  ('3.1.2.11 Materiais de Escritório - Administrativo', '3.1.2.11 Materiais de Escritório - Administrativo', 'Ocupação & Escritório', 'dre'),
  ('3.1.2.11 Materiais de Escritório - Administrativo', '3.1.2.11 Materiais de Escritório - Administrativo', 'Ocupação & Escritório', 'dfc'),
  ('3.1.2.12 Advocacia - Administrativo', '3.1.2.12 Advocacia - Administrativo', 'Assessorias & Consultorias', 'dre'),
  ('3.1.2.12 Advocacia - Administrativo', '3.1.2.12 Advocacia - Administrativo', 'Assessorias & Consultorias', 'dfc'),
  ('3.1.2.13 Contabilidade - Administrativo', '3.1.2.13 Contabilidade - Administrativo', 'Assessorias & Consultorias', 'dre'),
  ('3.1.2.13 Contabilidade - Administrativo', '3.1.2.13 Contabilidade - Administrativo', 'Assessorias & Consultorias', 'dfc'),
  ('3.1.2.14 Taxas e Cartório - Administrativo', '3.1.2.14 Taxas e Cartório - Administrativo', 'Outras despesas Adm', 'dre'),
  ('3.1.2.14 Taxas e Cartório - Administrativo', '3.1.2.14 Taxas e Cartório - Administrativo', 'Outras Despesas Adm', 'dfc'),
  ('3.1.2.15 Uniformes e Crachás - Administrativo', '3.1.2.15 Uniformes e Crachás - Administrativo', 'Outras despesas Adm', 'dre'),
  ('3.1.2.15 Uniformes e Crachás - Administrativo', '3.1.2.15 Uniformes e Crachás - Administrativo', 'Outras Despesas Adm', 'dfc'),
  ('3.1.2.16 Emissão NF - Administrativo', '3.1.2.16 Emissão NF - Administrativo', 'Meios de Pagamento', 'dre'),
  ('3.1.2.16 Emissão NF - Administrativo', '3.1.2.16 Emissão NF - Administrativo', 'Meios de Pagamento', 'dfc'),
  ('3.1.2.17 Cobrança Clientes - Administrativo', '3.1.2.17 Cobrança Clientes - Administrativo', 'Meios de Pagamento', 'dre'),
  ('3.1.2.17 Cobrança Clientes - Administrativo', '3.1.2.17 Cobrança Clientes - Administrativo', 'Meios de Pagamento', 'dfc'),
  ('3.1.2.18 Juros de Antecipação', '3.1.2.18 Juros de Antecipação', '(-) Juros', 'dre'),
  ('3.1.2.18 Juros de Antecipação', '3.1.2.18 Juros de Antecipação', '(-) Juros', 'dfc'),
  ('3.1.2.18 Outros - Administrativo', '3.1.2.18 Outros - Administrativo', 'Outras despesas Adm', 'dre'),
  ('3.1.2.18 Outros - Administrativo', '3.1.2.18 Outros - Administrativo', 'Outras Despesas Adm', 'dfc'),
  ('3.1.2.19 Outros - Administrativo', '3.1.2.19 Outros - Administrativo', 'Outras despesas Adm', 'dre'),
  ('3.1.2.19 Outros - Administrativo', '3.1.2.19 Outros - Administrativo', 'Outras Despesas Adm', 'dfc'),
  ('3.1.2.2 Serviços de Terceiros - Administrativo', '3.1.2.2 Serviços de Terceiros - Administrativo', 'Outras despesas Adm', 'dre'),
  ('3.1.2.2 Serviços de Terceiros - Administrativo', '3.1.2.2 Serviços de Terceiros - Administrativo', 'Outras Despesas Adm', 'dfc'),
  ('3.1.2.20 Outros - Administrativo', '3.1.2.20 Outros - Administrativo', 'Outras despesas Adm', 'dre'),
  ('3.1.2.20 Outros - Administrativo', '3.1.2.20 Outros - Administrativo', 'Outras Despesas Adm', 'dfc'),
  ('3.1.2.21 Outros - Administrativo', '3.1.2.21 Outros - Administrativo', 'Outras despesas Adm', 'dre'),
  ('3.1.2.21 Outros - Administrativo', '3.1.2.21 Outros - Administrativo', 'Outras Despesas Adm', 'dfc'),
  ('3.2.22 Diretores - Administrativo', '3.2.22 Diretores - Administrativo', 'Equipe Administrativa', 'dre'),
  ('3.2.22 Diretores - Administrativo', '3.2.22 Diretores - Administrativo', 'Equipe Administrativa', 'dfc'),
  ('3.1.2.3 Consultorias - Administrativo', '3.1.2.3 Consultorias - Administrativo', 'Assessorias & Consultorias', 'dre'),
  ('3.1.2.3 Consultorias - Administrativo', '3.1.2.3 Consultorias - Administrativo', 'Assessorias & Consultorias', 'dfc'),
  ('3.1.2.4 Transportes e Viagens - Administrativo', '3.1.2.4 Transportes e Viagens - Administrativo', 'Viagens & Transportes Adm', 'dre'),
  ('3.1.2.4 Transportes e Viagens - Administrativo', '3.1.2.4 Transportes e Viagens - Administrativo', 'Viagens & Transportes Adm', 'dfc'),
  ('3.1.2.5 Qualificação - Administrativo', '3.1.2.5 Qualificação - Administrativo', 'Outras despesas Adm', 'dre'),
  ('3.1.2.5 Qualificação - Administrativo', '3.1.2.5 Qualificação - Administrativo', 'Outras Despesas Adm', 'dfc'),
  ('3.1.2.6 Confraternizações - Administrativo', '3.1.2.6 Confraternizações - Administrativo', 'Outras despesas Adm', 'dre'),
  ('3.1.2.6 Confraternizações - Administrativo', '3.1.2.6 Confraternizações - Administrativo', 'Outras Despesas Adm', 'dfc'),
  ('3.1.2.8 Condomínio - Administrativo', '3.1.2.8 Condomínio - Administrativo', 'Ocupação & Escritório', 'dre'),
  ('3.1.2.8 Condomínio - Administrativo', '3.1.2.8 Condomínio - Administrativo', 'Ocupação & Escritório', 'dfc'),
  ('3.1.2.9 Energia - Administrativo', '3.1.2.9 Energia - Administrativo', 'Ocupação & Escritório', 'dre'),
  ('3.1.2.9 Energia - Administrativo', '3.1.2.9 Energia - Administrativo', 'Ocupação & Escritório', 'dfc'),
  ('3.1.3.1 Softwares - Marketing', '3.1.3.1 Softwares - Marketing', 'Softwares Marketing & Vendas', 'dre'),
  ('3.1.3.1 Softwares - Marketing', '3.1.3.1 Softwares - Marketing', 'Softwares Marketing & Vendas', 'dfc'),
  ('3.1.3.2 Serviços de Terceiros - Marketing', '3.1.3.2 Serviços de Terceiros - Marketing', 'Agências & Consultorias', 'dre'),
  ('3.1.3.2 Serviços de Terceiros - Marketing', '3.1.3.2 Serviços de Terceiros - Marketing', 'Agências & Consultorias', 'dfc'),
  ('3.1.3.3 Consultorias e Agências - Marketing', '3.1.3.3 Consultorias e Agências - Marketing', 'Agências & Consultorias', 'dre'),
  ('3.1.3.3 Consultorias e Agências - Marketing', '3.1.3.3 Consultorias e Agências - Marketing', 'Agências & Consultorias', 'dfc'),
  ('3.1.3.4 Transportes e Viagens - Marketing', '3.1.3.4 Transportes e Viagens - Marketing', 'Viagens & Transportes Mkt', 'dre'),
  ('3.1.3.4 Transportes e Viagens - Marketing', '3.1.3.4 Transportes e Viagens - Marketing', 'Viagens & Transportes Mkt', 'dfc'),
  ('3.1.3.5 Qualificação - Marketing', '3.1.3.5 Qualificação - Marketing', 'Outras despesas Mkt', 'dre'),
  ('3.1.3.5 Qualificação - Marketing', '3.1.3.5 Qualificação - Marketing', 'Outras Despesas Mkt', 'dfc'),
  ('3.1.3.6 Confraternizações - Marketing', '3.1.3.6 Confraternizações - Marketing', 'Outras despesas Mkt', 'dre'),
  ('3.1.3.6 Confraternizações - Marketing', '3.1.3.6 Confraternizações - Marketing', 'Outras Despesas Mkt', 'dfc'),
  ('3.1.3.7 Adsense - Marketing', '3.1.3.7 Adsense - Marketing', 'Campanhas de Mídia Paga', 'dre'),
  ('3.1.3.7 Adsense - Marketing', '3.1.3.7 Adsense - Marketing', 'Campanhas de Mídia Paga', 'dfc'),
  ('3.1.3.8 Eventos e Feiras - Marketing', '3.1.3.8 Eventos e Feiras - Marketing', 'Eventos e Feiras', 'dre'),
  ('3.1.3.8 Eventos e Feiras - Marketing', '3.1.3.8 Eventos e Feiras - Marketing', 'Eventos e Feiras', 'dfc'),
  ('3.1.3.9 Outros - Marketing', '3.1.3.9 Outros - Marketing', 'Outras despesas Mkt', 'dre'),
  ('3.1.3.9 Outros - Marketing', '3.1.3.9 Outros - Marketing', 'Outras Despesas Mkt', 'dfc'),
  ('3.1.3.10 Influencer Fixo', '3.1.3.10 Influencer Fixo', 'Campanhas de Outros Canais', 'dre'),
  ('3.1.3.10 Influencer Fixo', '3.1.3.10 Influencer Fixo', 'Campanhas de Outros Canais', 'dfc'),
  ('3.1.3.11 Consultor / Parceiro Variável', '3.1.3.11 Consultor / Parceiro Variável', 'Comissões Consultores / Parceiros', 'dre'),
  ('3.1.3.11 Consultor / Parceiro Variável', '3.1.3.11 Consultor / Parceiro Variável', 'Comissões Consultores / Parceiros', 'dfc'),
  ('3.1.4.1 Softwares - Comercial', '3.1.4.1 Softwares - Comercial', 'Softwares Marketing & Vendas', 'dre'),
  ('3.1.4.1 Softwares - Comercial', '3.1.4.1 Softwares - Comercial', 'Softwares Marketing & Vendas', 'dfc'),
  ('3.1.4.2 Serviços de Terceiros - Comercial', '3.1.4.2 Serviços de Terceiros - Comercial', 'Agências & Consultorias', 'dre'),
  ('3.1.4.2 Serviços de Terceiros - Comercial', '3.1.4.2 Serviços de Terceiros - Comercial', 'Agências & Consultorias', 'dfc'),
  ('3.1.4.3 Consultorias - Comercial', '3.1.4.3 Consultorias - Comercial', 'Agências & Consultorias', 'dre'),
  ('3.1.4.3 Consultorias - Comercial', '3.1.4.3 Consultorias - Comercial', 'Agências & Consultorias', 'dfc'),
  ('3.1.4.4 Transportes e Viagens - Comercial', '3.1.4.4 Transportes e Viagens - Comercial', 'Viagens & Transportes Mkt', 'dre'),
  ('3.1.4.4 Transportes e Viagens - Comercial', '3.1.4.4 Transportes e Viagens - Comercial', 'Viagens & Transportes Mkt', 'dfc'),
  ('3.1.4.5 Qualificação - Comercial', '3.1.4.5 Qualificação - Comercial', 'Outras despesas Mkt', 'dre'),
  ('3.1.4.5 Qualificação - Comercial', '3.1.4.5 Qualificação - Comercial', 'Outras Despesas Mkt', 'dfc'),
  ('3.1.4.6 Confraternizações - Comercial', '3.1.4.6 Confraternizações - Comercial', 'Outras despesas Mkt', 'dre'),
  ('3.1.4.6 Confraternizações - Comercial', '3.1.4.6 Confraternizações - Comercial', 'Outras Despesas Mkt', 'dfc'),
  ('3.1.4.7 Outros - Comercial', '3.1.4.7 Outros - Comercial', 'Outras despesas Mkt', 'dre'),
  ('3.1.4.7 Outros - Comercial', '3.1.4.7 Outros - Comercial', 'Outras Despesas Mkt', 'dfc'),
  ('3.1.4.8 Outros - Comercial', '3.1.4.8 Outros - Comercial', 'Outras despesas Mkt', 'dre'),
  ('3.1.4.8 Outros - Comercial', '3.1.4.8 Outros - Comercial', 'Outras Despesas Mkt', 'dfc'),
  ('3.1.4.7 Consultoria - Operacional', '3.1.4.7 Consultoria - Operacional', 'Agências & Consultorias', 'dre'),
  ('3.1.4.7 Consultoria - Operacional', '3.1.4.7 Consultoria - Operacional', 'Agências & Consultorias', 'dfc'),
  ('3.1.5.1 Softwares - Tecnologia', '3.1.5.1 Softwares - Tecnologia', 'Softwares Operacionais', 'dre'),
  ('3.1.5.1 Softwares - Tecnologia', '3.1.5.1 Softwares - Tecnologia', 'Softwares Operacionais', 'dfc'),
  ('3.1.5.2 Serviços de Terceiros - Tecnologia', '3.1.5.2 Serviços de Terceiros - Tecnologia', 'Assessorias & Consultorias', 'dre'),
  ('3.1.5.2 Serviços de Terceiros - Tecnologia', '3.1.5.2 Serviços de Terceiros - Tecnologia', 'Assessorias & Consultorias', 'dfc'),
  ('3.1.5.3 Consultorias - Tecnologia', '3.1.5.3 Consultorias - Tecnologia', 'Assessorias & Consultorias', 'dre'),
  ('3.1.5.3 Consultorias - Tecnologia', '3.1.5.3 Consultorias - Tecnologia', 'Assessorias & Consultorias', 'dfc'),
  ('3.1.5.4 Transportes e Viagens - Tecnologia', '3.1.5.4 Transportes e Viagens - Tecnologia', 'Viagens & Transportes Adm', 'dre'),
  ('3.1.5.4 Transportes e Viagens - Tecnologia', '3.1.5.4 Transportes e Viagens - Tecnologia', 'Viagens & Transportes Adm', 'dfc'),
  ('3.1.5.5 Qualificação - Tecnologia', '3.1.5.5 Qualificação - Tecnologia', 'Outras despesas Adm', 'dre'),
  ('3.1.5.5 Qualificação - Tecnologia', '3.1.5.5 Qualificação - Tecnologia', 'Outras Despesas Adm', 'dfc'),
  ('3.1.5.6 Confraternizações - Tecnologia', '3.1.5.6 Confraternizações - Tecnologia', 'Outras despesas Adm', 'dre'),
  ('3.1.5.6 Confraternizações - Tecnologia', '3.1.5.6 Confraternizações - Tecnologia', 'Outras Despesas Adm', 'dfc'),
  ('3.1.5.7 Outros - Tecnologia', '3.1.5.7 Outros - Tecnologia', 'Outras despesas Adm', 'dre'),
  ('3.1.5.7 Outros - Tecnologia', '3.1.5.7 Outros - Tecnologia', 'Outras Despesas Adm', 'dfc'),
  ('3.1.5.8 Outros - Tecnologia', '3.1.5.8 Outros - Tecnologia', 'Outras despesas Adm', 'dre'),
  ('3.1.5.8 Outros - Tecnologia', '3.1.5.8 Outros - Tecnologia', 'Outras Despesas Adm', 'dfc'),
  ('3.1.5.9 Outros - Tecnologia', '3.1.5.9 Outros - Tecnologia', 'Outras despesas Adm', 'dre'),
  ('3.1.5.9 Outros - Tecnologia', '3.1.5.9 Outros - Tecnologia', 'Outras Despesas Adm', 'dfc'),
  ('3.2.1 CMV - Operação', '3.2.1 CMV - Operação', 'CMV Materiais', 'dre'),
  ('3.2.1 CMV - Operação', '3.2.1 CMV - Operação', 'CMV Materiais', 'dfc'),
  ('3.2.2 Frete - Operação', '3.2.2 Frete - Operação', 'Outros Custos', 'dre'),
  ('3.2.2 Frete - Operação', '3.2.2 Frete - Operação', 'Outros Custos', 'dfc'),
  ('3.2.3. Meios de Pagamento - Administrativo', '3.2.3. Meios de Pagamento - Administrativo', 'Meios de Pagamento', 'dre'),
  ('3.2.3. Meios de Pagamento - Administrativo', '3.2.3. Meios de Pagamento - Administrativo', 'Meios de Pagamento', 'dfc'),
  ('3.2.4. Servidor - Tecnologia', '3.2.4. Servidor - Tecnologia', 'Servidor', 'dre'),
  ('3.2.4. Servidor - Tecnologia', '3.2.4. Servidor - Tecnologia', 'Servidor', 'dfc'),
  ('3.2.5. Software - Operação', '3.2.5. Software - Operação', 'Softwares Operacionais', 'dre'),
  ('3.2.5. Software - Operação', '3.2.5. Software - Operação', 'Softwares Operacionais', 'dfc'),
  ('3.2.6 MGM', '3.2.6 MGM', 'MGM', 'dre'),
  ('3.2.6 MGM', '3.2.6 MGM', 'MGM', 'dfc'),
  ('3.2.7. Pessoal - Operação', '3.2.7. Pessoal - Operação', 'Equipe Operacional', 'dre'),
  ('3.2.7. Pessoal - Operação', '3.2.7. Pessoal - Operação', 'Equipe Operacional', 'dfc'),
  ('3.2.7.1 Pessoal - Onboarding', '3.2.7.1 Pessoal - Onboarding', 'Equipe Operacional', 'dre'),
  ('3.2.7.1 Pessoal - Onboarding', '3.2.7.1 Pessoal - Onboarding', 'Equipe Operacional', 'dfc'),
  ('3.2.7.1. Pessoal - Onboarding', '3.2.7.1. Pessoal - Onboarding', 'Equipe Onboarding', 'dre'),
  ('3.2.7.1. Pessoal - Onboarding', '3.2.7.1. Pessoal - Onboarding', 'Equipe Onboarding', 'dfc'),
  ('3.2.7.2. Pessoal - Sucesso', '3.2.7.2. Pessoal - Sucesso', 'Equipe Operacional', 'dre'),
  ('3.2.7.2. Pessoal - Sucesso', '3.2.7.2. Pessoal - Sucesso', 'Equipe Operacional', 'dfc'),
  ('3.2.7.2. Pessoal - Suporte', '3.2.7.2. Pessoal - Suporte', 'Equipe Operacional', 'dre'),
  ('3.2.7.2. Pessoal - Suporte', '3.2.7.2. Pessoal - Suporte', 'Equipe Operacional', 'dfc'),
  ('3.2.7.3. Pessoal - Sucesso', '3.2.7.3. Pessoal - Sucesso', 'Equipe Operacional', 'dre'),
  ('3.2.7.3. Pessoal - Sucesso', '3.2.7.3. Pessoal - Sucesso', 'Equipe Operacional', 'dfc'),
  ('3.2.7.4. Escala - Suporte', '3.2.7.4. Escala - Suporte', 'Equipe Operacional', 'dre'),
  ('3.2.7.4. Escala - Suporte', '3.2.7.4. Escala - Suporte', 'Equipe Operacional', 'dfc'),
  ('3.3.1 Devolução Empréstimo', '3.3.1 Devolução Empréstimo', '(-) Amortização de Financiamentos', 'dfc'),
  ('3.3.1 Devolução Empréstimo Outros', '3.3.1 Devolução Empréstimo Outros', '(-) Amortização de Financiamentos', 'dfc'),
  ('3.3.2 Amortização de Parcelas', '3.3.2 Amortização de Parcelas', '(-) Amortização de Financiamentos', 'dfc'),
  ('3.3.3 Baixa de recebíveis', '3.3.3 Baixa de recebíveis', 'Abatimento de Antecipação da Receita', 'dfc'),
  ('3.3.4 Juros Financiamento', '3.3.4 Juros Financiamento', '(-) Juros', 'dre'),
  ('3.3.4 Juros Financiamento', '3.3.4 Juros Financiamento', '(-) Juros', 'dfc'),
  ('3.3.4 Taxa de Operação de Crédito', '3.3.4 Taxa de Operação de Crédito', '(-) IOF', 'dre'),
  ('3.3.4 Taxa de Operação de Crédito', '3.3.4 Taxa de Operação de Crédito', '(-) IOF', 'dfc'),
  ('3.3.5 IOF Financiamento', '3.3.5 IOF Financiamento', '(-) IOF', 'dre'),
  ('3.3.5 IOF Financiamento', '3.3.5 IOF Financiamento', '(-) IOF', 'dfc'),
  ('3.4.1 CAPEX Equipamentos', '3.4.1 CAPEX Equipamentos', '(-) Compra de Equipamentos', 'dfc'),
  ('4.1 Devolução de Assinatura', '4.1 Devolução de Assinatura', 'Devoluções', 'dre'),
  ('4.1 Devolução de Assinatura', '4.1 Devolução de Assinatura', 'Devoluções', 'dfc'),
  ('6.1 Estorno de cliente ASAAS', '6.1 Estorno de cliente ASAAS', 'Devoluções', 'dre'),
  ('6.1 Estorno de cliente ASAAS', '6.1 Estorno de cliente ASAAS', 'Devoluções', 'dfc'),
  ('6.1 Estorno e devoluções', '6.1 Estorno e devoluções', 'Devoluções', 'dre'),
  ('6.1 Estorno e devoluções', '6.1 Estorno e devoluções', 'Devoluções', 'dfc'),
  ('Assinatura', 'Assinatura', 'Receita de Assinaturas', 'dre'),
  ('Assinatura', 'Assinatura', 'Receita de Assinaturas', 'dfc'),
  ('Material', 'Material', 'Receita com Materiais', 'dre'),
  ('Material', 'Material', 'Receita com Materiais', 'dfc'),
  ('3.4.2 CAPEX Estrutura', '3.4.2 CAPEX Estrutura', '(-) Investimentos em Estrutura', 'dfc'),
  ('3.1.1.16 Premiação - Administrativo', '3.1.1.16 Premiação - Administrativo', 'Premiações', 'dre'),
  ('3.1.1.16 Premiação - Administrativo', '3.1.1.16 Premiação - Administrativo', 'Premiações', 'dfc'),
  ('Alimentação', 'Alimentação', 'Outras despesas Adm', 'dre'),
  ('Alimentação', 'Alimentação', 'Outras Despesas Adm', 'dfc'),
  ('2.7 IOF', '2.7 IOF', '(-) IOF', 'dre'),
  ('2.7 IOF', '2.7 IOF', '(-) IOF', 'dfc'),
  ('5.1 Estorno - Eventos e Feiras', '5.1 Estorno - Eventos e Feiras', '(-) Estorno de Compras', 'dre'),
  ('5.1 Estorno - Eventos e Feiras', '5.1 Estorno - Eventos e Feiras', '(-) Estorno de Compras', 'dfc'),
  ('5.2 Estornos - Uniformes e Crachás', '5.2 Estornos - Uniformes e Crachás', '(-) Estorno de Compras', 'dre'),
  ('5.2 Estornos - Uniformes e Crachás', '5.2 Estornos - Uniformes e Crachás', '(-) Estorno de Compras', 'dfc'),
  ('5.3 Estorno - Materiais de Escritório', '5.3 Estorno - Materiais de Escritório', '(-) Estorno de Compras', 'dre'),
  ('5.3 Estorno - Materiais de Escritório', '5.3 Estorno - Materiais de Escritório', '(-) Estorno de Compras', 'dfc'),
  ('5.4 Estorno - Qualificação', '5.4 Estorno - Qualificação', '(-) Estorno de Compras', 'dre'),
  ('5.4 Estorno - Qualificação', '5.4 Estorno - Qualificação', '(-) Estorno de Compras', 'dfc'),
  ('5.4.1 Estorno - Qualificação: Marketing', '5.4.1 Estorno - Qualificação: Marketing', '(-) Estorno de Compras', 'dre'),
  ('5.4.1 Estorno - Qualificação: Marketing', '5.4.1 Estorno - Qualificação: Marketing', '(-) Estorno de Compras', 'dfc'),
  ('3.3.5 Empréstimos Adquiridos', '3.3.5 Empréstimos Adquiridos', '(-) Amortização de Financiamentos', 'dfc'),
  ('Compra de Participação', 'Compra de Participação', '(-) Compra de Participação', 'dfc'),
  ('3.2.7.5. Escala - Onboarding', '3.2.7.5. Escala - Onboarding', 'Equipe Onboarding', 'dre'),
  ('3.2.7.5. Escala - Onboarding', '3.2.7.5. Escala - Onboarding', 'Equipe Onboarding', 'dfc'),
  ('Despesas com Captação', 'Despesas com Captação', '(-) Rodada de Investimentos', 'dfc'),
  ('Construção, Reformas e Melhorias', 'Construção, Reformas e Melhorias', '(-) Investimentos em Estrutura', 'dfc'),
  ('Depósitos e Caução', 'Depósitos e Caução', 'Depósitos e Caução', 'dfc'),
  ('2.9 Imposto Retido', '2.9 Imposto Retido', 'Outras despesas Adm', 'dre'),
  ('2.9 Imposto Retido', '2.9 Imposto Retido', 'Outras Despesas Adm', 'dfc'),
  ('3.1.4.8 Telefone e Internet - Comercial', '3.1.4.8 Telefone e Internet - Comercial', 'Ocupação & Escritório', 'dre'),
  ('3.1.4.8 Telefone e Internet - Comercial', '3.1.4.8 Telefone e Internet - Comercial', 'Ocupação & Escritório', 'dfc'),
  ('3.1.2.20 Segurança - Administrativo', '3.1.2.20 Segurança - Administrativo', 'Ocupação & Escritório', 'dre'),
  ('3.1.2.20 Segurança - Administrativo', '3.1.2.20 Segurança - Administrativo', 'Ocupação & Escritório', 'dfc'),
  ('3.1.2.21 Limpeza - Administrativo', '3.1.2.21 Limpeza - Administrativo', 'Ocupação & Escritório', 'dre'),
  ('3.1.2.21 Limpeza - Administrativo', '3.1.2.21 Limpeza - Administrativo', 'Ocupação & Escritório', 'dfc'),
  ('3.1.2.21 Água e Esgoto - Administrativo', '3.1.2.21 Água e Esgoto - Administrativo', 'Ocupação & Escritório', 'dre'),
  ('3.1.2.21 Água e Esgoto - Administrativo', '3.1.2.21 Água e Esgoto - Administrativo', 'Ocupação & Escritório', 'dfc'),
  ('Aportes', 'Aportes', '(+) Novos Empréstimos & Financiamentos', 'dfc'),
  ('1.1.5. Receita com Locações', '1.1.5. Receita com Locações', '(+) Resultado Não Operacional', 'dre'),
  ('1.1.5. Receita com Locações', '1.1.5. Receita com Locações', '(+) Resultado Não Operacional', 'dfc'),
  ('Tarifas', 'Tarifas', '(-) Depesas Financeiras', 'dre'),
  ('Tarifas', 'Tarifas', '(-) Depesas Financeiras', 'dfc'),
  ('Juros Pagos', 'Juros Pagos', '(-) Juros', 'dre'),
  ('Juros Pagos', 'Juros Pagos', '(-) Juros', 'dfc'),
  ('Multas pagas', 'Multas pagas', 'Outras despesas Adm', 'dre'),
  ('Multas pagas', 'Multas pagas', 'Outras Despesas Adm', 'dfc')
ON CONFLICT (codigo_categoria, demonstrativo) DO UPDATE
  SET rubrica = excluded.rubrica, descricao_categoria = excluded.descricao_categoria, updated_at = now();
